name: gcs_resumable_upload
description: Upload files to Google Cloud Storage using signed urls and resumable upload.
version: 1.0.0
# homepage: https://www.example.com
authors:
  - "dudi@vizo.dev"

repository: "https://github.com/vizodev/gcs_resumable_upload.git"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dio: ">=4.0.6 <6.0.0"
  crypto: ^3.0.2
  path: ^1.8.3
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
